name: bri-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - nltk>=3.7
  - spacy>=3.4.0
  - yfinance>=0.1.70
  - requests>=2.28.0
  - tqdm>=4.64.0
  - python-dotenv>=0.19.0
  - pip:
    - sentence-transformers>=2.2.0
    - transformers>=4.20.0
    - torch>=1.12.0
    - tweepy>=4.10.0
    - praw>=7.6.0
    - plotly>=5.10.0
    - statsmodels>=0.13.0
    - arch>=5.3.0
    - streamlit>=1.12.0
    - pytest>=7.1.0
    - pytest-cov>=3.0.0
